"""add created_at to folders

Revision ID: 9269ae2266e4
Revises: 549e488a596e
Create Date: 2026-06-23 23:52:49.407371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9269ae2266e4'
down_revision: Union[str, Sequence[str], None] = '549e488a596e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('paper_authors', sa.Column('associated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_authors', 'associated_at')
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###
